export const REQUEST_CURRENT_LOCATION = "REQUEST_CURRENT_LOCATION";
export const REQUEST_NEARBY_STATIONS = "REQUEST_NEARBY_STATIONS";

export const RECEIVE_CURRENT_LOCATION = "REQUEST_CURRENT_LOCATION";
export const RECEIVE_NEARBY_STATIONS = "REQUEST_NEARBY_STATIONS";
